# Generated by Django 4.2.15 on 2024-11-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadach', '0029_conflict_schedule101_index_schedule111_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListEror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название ошибки:')),
            ],
        ),
    ]
